apiVersion: v1
kind: Secret
metadata:
  name: {{ include "router.fullname" . }}-api-keys
  labels:
    app.kubernetes.io/name: {{ include "router.name" . }}
    helm.sh/chart: {{ include "router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  qwen3ApiKey: {{ .Values.secrets.qwen3ApiKey | b64enc | quote }}
  rerankApiKey: {{ .Values.secrets.rerankApiKey | b64enc | quote }}
