apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qwen3-embed.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "qwen3-embed.name" . }}
    helm.sh/chart: {{ include "qwen3-embed.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ .Values.env.apiKey | b64enc | quote }}
